"""initial schema

Revision ID: 084d3051bff7
Revises: 
Create Date: 2026-03-29 01:03:42.150517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084d3051bff7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firearms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('calibre', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_issue_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('guards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('cell_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_number')
    )
    op.create_table('guard_firearm_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guard_id', sa.String(length=36), nullable=False),
    sa.Column('firearm_id', sa.String(length=36), nullable=False),
    sa.Column('is_permitted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firearm_id'], ['firearms.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guard_id', 'firearm_id', name='uq_guard_firearm')
    )
    op.create_table('permits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('permit_number', sa.String(length=30), nullable=False),
    sa.Column('guard_id', sa.String(length=36), nullable=False),
    sa.Column('firearm_id', sa.String(length=36), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('valid_date', sa.Date(), nullable=True),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['firearm_id'], ['firearms.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permit_number')
    )
    op.create_table('register_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guard_id', sa.String(length=36), nullable=False),
    sa.Column('firearm_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actioned_by', sa.String(length=36), nullable=False),
    sa.Column('actioned_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['firearm_id'], ['firearms.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guard_id', sa.String(length=36), nullable=False),
    sa.Column('firearm_id', sa.String(length=36), nullable=False),
    sa.Column('issued_by', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('permit_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['firearm_id'], ['firearms.id'], ),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firearm_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register')
    op.drop_table('register_history')
    op.drop_table('permits')
    op.drop_table('guard_firearm_permissions')
    op.drop_table('guards')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('firearms')
    # ### end Alembic commands ###
