"""add_guard_competency_fields_and_cit_routes

Revision ID: 1210dc2fbd2d
Revises: 4014436835fd
Create Date: 2026-03-30 21:03:46.131752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1210dc2fbd2d'
down_revision: Union[str, None] = '4014436835fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guard_cit_routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guard_id', sa.String(length=36), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('cell_phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['guard_id'], ['guards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('guards', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('guards', sa.Column('personnel_number', sa.String(length=20), nullable=True))
    op.add_column('guards', sa.Column('saps_comp_carbine', sa.String(length=50), nullable=True))
    op.add_column('guards', sa.Column('saps_expiry_carbine', sa.Date(), nullable=True))
    op.add_column('guards', sa.Column('saps_comp_handgun', sa.String(length=50), nullable=True))
    op.add_column('guards', sa.Column('saps_expiry_handgun', sa.Date(), nullable=True))
    op.add_column('guards', sa.Column('saps_comp_rifle', sa.String(length=50), nullable=True))
    op.add_column('guards', sa.Column('saps_expiry_rifle', sa.Date(), nullable=True))
    op.add_column('guards', sa.Column('saps_comp_shotgun', sa.String(length=50), nullable=True))
    op.add_column('guards', sa.Column('saps_expiry_shotgun', sa.Date(), nullable=True))
    op.add_column('guards', sa.Column('permitted_carbine', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('guards', sa.Column('permitted_handgun', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('guards', sa.Column('permitted_rifle', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('guards', sa.Column('permitted_shotgun', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guards', 'permitted_shotgun')
    op.drop_column('guards', 'permitted_rifle')
    op.drop_column('guards', 'permitted_handgun')
    op.drop_column('guards', 'permitted_carbine')
    op.drop_column('guards', 'saps_expiry_shotgun')
    op.drop_column('guards', 'saps_comp_shotgun')
    op.drop_column('guards', 'saps_expiry_rifle')
    op.drop_column('guards', 'saps_comp_rifle')
    op.drop_column('guards', 'saps_expiry_handgun')
    op.drop_column('guards', 'saps_comp_handgun')
    op.drop_column('guards', 'saps_expiry_carbine')
    op.drop_column('guards', 'saps_comp_carbine')
    op.drop_column('guards', 'personnel_number')
    op.drop_column('guards', 'region')
    op.drop_table('guard_cit_routes')
    # ### end Alembic commands ###
