"""add_user_permissions_and_profile_fields

Revision ID: 4014436835fd
Revises: 4295c76d2d5c
Create Date: 2026-03-30 20:59:51.981891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4014436835fd'
down_revision: Union[str, None] = '4295c76d2d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personnel_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('psira_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('competency', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('id_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('perm_new_permits', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_return_permits', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_manage_weapons', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_manage_staff', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_access_database', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_send_whatsapp', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_view_register_history', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_system_admin', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_add_user', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_modify_user', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_change_passwords', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_clear_logs', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_carbine', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_handgun', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_rifle', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('perm_shotgun', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'perm_shotgun')
    op.drop_column('users', 'perm_rifle')
    op.drop_column('users', 'perm_handgun')
    op.drop_column('users', 'perm_carbine')
    op.drop_column('users', 'perm_clear_logs')
    op.drop_column('users', 'perm_change_passwords')
    op.drop_column('users', 'perm_modify_user')
    op.drop_column('users', 'perm_add_user')
    op.drop_column('users', 'perm_system_admin')
    op.drop_column('users', 'perm_view_register_history')
    op.drop_column('users', 'perm_send_whatsapp')
    op.drop_column('users', 'perm_access_database')
    op.drop_column('users', 'perm_manage_staff')
    op.drop_column('users', 'perm_manage_weapons')
    op.drop_column('users', 'perm_return_permits')
    op.drop_column('users', 'perm_new_permits')
    op.drop_column('users', 'id_number')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'competency')
    op.drop_column('users', 'psira_number')
    op.drop_column('users', 'personnel_number')
    # ### end Alembic commands ###
