"""add_permit_ammunition_and_inspection_fields

Revision ID: 995cc4b956f9
Revises: afcaf906e07c
Create Date: 2026-03-30 21:13:22.666633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995cc4b956f9'
down_revision: Union[str, None] = 'afcaf906e07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permits', sa.Column('rounds_issued', sa.Integer(), nullable=True))
    op.add_column('permits', sa.Column('period_from_time', sa.Time(), nullable=True))
    op.add_column('permits', sa.Column('valid_until_time', sa.Time(), nullable=True))
    op.add_column('permits', sa.Column('cit_cell_route', sa.String(length=100), nullable=True))
    op.add_column('permits', sa.Column('witness', sa.String(length=100), nullable=True))
    op.add_column('permits', sa.Column('saps_competency_number', sa.String(length=50), nullable=True))
    op.add_column('permits', sa.Column('rounds_returned', sa.Integer(), nullable=True))
    op.add_column('permits', sa.Column('firearm_returned_correct', sa.Boolean(), nullable=True))
    op.add_column('permits', sa.Column('in_order', sa.Boolean(), nullable=True))
    op.add_column('permits', sa.Column('posted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('permits', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permits', 'remarks')
    op.drop_column('permits', 'posted')
    op.drop_column('permits', 'in_order')
    op.drop_column('permits', 'firearm_returned_correct')
    op.drop_column('permits', 'rounds_returned')
    op.drop_column('permits', 'saps_competency_number')
    op.drop_column('permits', 'witness')
    op.drop_column('permits', 'cit_cell_route')
    op.drop_column('permits', 'valid_until_time')
    op.drop_column('permits', 'period_from_time')
    op.drop_column('permits', 'rounds_issued')
    # ### end Alembic commands ###
