"""make_firearm_type_nullable_add_description

Revision ID: afcaf906e07c
Revises: 1210dc2fbd2d
Create Date: 2026-03-30 21:07:21.481656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afcaf906e07c'
down_revision: Union[str, None] = '1210dc2fbd2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('firearms', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('firearms', 'type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('firearms', 'calibre',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('firearms', 'calibre',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('firearms', 'type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('firearms', 'description')
    # ### end Alembic commands ###
