"""add_register_ammunition_and_inspection_fields

Revision ID: c2fb0d8f1704
Revises: 995cc4b956f9
Create Date: 2026-03-31 06:46:09.709841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fb0d8f1704'
down_revision: Union[str, None] = '995cc4b956f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('ammunition_issued', sa.Integer(), nullable=True))
    op.add_column('register', sa.Column('firearm_inspected_correct', sa.Boolean(), nullable=True))
    op.add_column('register', sa.Column('cit_id', sa.String(length=50), nullable=True))
    op.add_column('register', sa.Column('responsible_person_name', sa.String(length=100), nullable=True))
    op.add_column('register_history', sa.Column('ammunition_issued', sa.Integer(), nullable=True))
    op.add_column('register_history', sa.Column('ammunition_returned', sa.Integer(), nullable=True))
    op.add_column('register_history', sa.Column('firearm_inspected_correct', sa.Boolean(), nullable=True))
    op.add_column('register_history', sa.Column('firearm_returned_correct', sa.Boolean(), nullable=True))
    op.add_column('register_history', sa.Column('permit_returned', sa.Boolean(), nullable=True))
    op.add_column('register_history', sa.Column('guard_signature', sa.String(length=255), nullable=True))
    op.add_column('register_history', sa.Column('authorising_officer_signature', sa.String(length=255), nullable=True))
    op.add_column('register_history', sa.Column('audit_signature', sa.String(length=255), nullable=True))
    op.add_column('register_history', sa.Column('cit_id', sa.String(length=50), nullable=True))
    op.add_column('register_history', sa.Column('responsible_person_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register_history', 'responsible_person_name')
    op.drop_column('register_history', 'cit_id')
    op.drop_column('register_history', 'audit_signature')
    op.drop_column('register_history', 'authorising_officer_signature')
    op.drop_column('register_history', 'guard_signature')
    op.drop_column('register_history', 'permit_returned')
    op.drop_column('register_history', 'firearm_returned_correct')
    op.drop_column('register_history', 'firearm_inspected_correct')
    op.drop_column('register_history', 'ammunition_returned')
    op.drop_column('register_history', 'ammunition_issued')
    op.drop_column('register', 'responsible_person_name')
    op.drop_column('register', 'cit_id')
    op.drop_column('register', 'firearm_inspected_correct')
    op.drop_column('register', 'ammunition_issued')
    # ### end Alembic commands ###
