"""add psira_number to guards, make id_number nullable

Revision ID: d9080158a181
Revises: 084d3051bff7
Create Date: 2026-03-30 08:14:05.083026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9080158a181'
down_revision: Union[str, None] = '084d3051bff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guards', sa.Column('psira_number', sa.String(length=20), nullable=True))
    op.alter_column('guards', 'id_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guards', 'id_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('guards', 'psira_number')
    # ### end Alembic commands ###
