"""add_guard_signin_account_and_signature_fields

Revision ID: e7efa56627a9
Revises: c2fb0d8f1704
Create Date: 2026-06-03 10:22:51.840241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7efa56627a9'
down_revision: Union[str, None] = 'c2fb0d8f1704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guards', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('guards', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('guards', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('guards', sa.Column('password_set_at', sa.DateTime(), nullable=True))
    op.add_column('guards', sa.Column('last_signin_at', sa.DateTime(), nullable=True))
    op.add_column('guards', sa.Column('reset_otp_hash', sa.String(length=255), nullable=True))
    op.add_column('guards', sa.Column('reset_otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('guards', sa.Column('reset_otp_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.create_unique_constraint('uq_guards_username', 'guards', ['username'])
    op.add_column('permits', sa.Column('guard_signed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('permits', sa.Column('guard_signed_at', sa.DateTime(), nullable=True))
    op.add_column('permits', sa.Column('guard_signature_method', sa.String(length=30), nullable=True))
    op.add_column('register', sa.Column('guard_signed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('register', sa.Column('guard_signed_at', sa.DateTime(), nullable=True))
    op.add_column('register_history', sa.Column('guard_signed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('register_history', sa.Column('guard_signed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register_history', 'guard_signed_at')
    op.drop_column('register_history', 'guard_signed')
    op.drop_column('register', 'guard_signed_at')
    op.drop_column('register', 'guard_signed')
    op.drop_column('permits', 'guard_signature_method')
    op.drop_column('permits', 'guard_signed_at')
    op.drop_column('permits', 'guard_signed')
    op.drop_constraint('uq_guards_username', 'guards', type_='unique')
    op.drop_column('guards', 'reset_otp_attempts')
    op.drop_column('guards', 'reset_otp_expires_at')
    op.drop_column('guards', 'reset_otp_hash')
    op.drop_column('guards', 'last_signin_at')
    op.drop_column('guards', 'password_set_at')
    op.drop_column('guards', 'must_change_password')
    op.drop_column('guards', 'hashed_password')
    op.drop_column('guards', 'username')
    # ### end Alembic commands ###
